version: "3"

services:
  cache:
    image: "redis:alpine"
    container_name: pagoda_cache
    ports:
      - "127.0.0.1:6379:6379"

  db:
    # PG 16 is currenly not supported https://github.com/ent/ent/issues/3750
    image: postgres:15-alpine
    container_name: pagoda_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1