// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FileStorage is the predicate function for filestorage builders.
type FileStorage func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
